# https://nixpacks.com/docs/configuration/file
providers = ["java", "node"]

[phases.setup]
nixPkgs = ["jdk21_headless", "nodejs_20"]

[phases.build]
cmds = ["cd backend && ./gradlew clean build -x test"]

[start]
cmd = "cd backend && java -jar build/libs/isl-playground-1.0.0.jar"

