# https://nixpacks.com/docs/configuration/file

[phases.setup]
nixPkgs = ["openjdk", "nodejs"]

[phases.build]
cmds = ["cd backend && ./gradlew clean build -x test"]

[start]
cmd = "cd backend && java -jar build/libs/isl-playground-1.0.0.jar"
nixPkgs = ["openjdk"]

# Test
